/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  Vachan Online: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

// module.exports = sidebars;

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  vachan: [
    "Introduction",
    {
      type: "category",
      label: "Website Navigation",
      link: {
        type: "generated-index",
      },
      items: ["landingPage", "studyBiblePage"],
    },
    {
      type: "category",
      label: "Features",
      collapsed: false,
      link: {
        type: "generated-index",
      },
      items: [
        "studyBible",
        "readBible",
        "signLanguageBible",
        "songs",
        "bibleStories",
        "commentaries",
        "infographics",
        "audioBible",
        "videos",
        "readingPlans",
        "dictionaries",
      ],
    },
    {
      type: "category",
      label: "User Login Features ",
      link: {
        type: "generated-index",
      },
      items: [
        "signUp",
        "signIn",
        "bookmarks",
        "highlights",
        "notes",
        "signOut",
      ],
    },
    "feedback",
    "contactUs",
  ],
};
